### PR TITLE
chore: update to ng 15

### LINKED ISSUE #337: Angular 15 update
Hi there,
Angular v15 has been available for some time now, so I was wondering if there are any plans on updating the angular-split?

### PR DESCRIPTION
**Pull request by kufuntu**
closes #337

### CODE REVIEW

**Comment by kufuntu** [comment]
@beeman can you check the PR please?

**Comment by beeman** [comment]
> @beeman can you check the PR please?

Thanks for the PR! I will review it and push out an update of `angular-split`.

**Comment by beeman** [comment]
This has been released in [v15.0.0](https://www.npmjs.com/package/angular-split/v/15.0.0) 🎉

**Comment by Jefiozie** [comment]
@all-contributors please add @kufuntu for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
