### PR TITLE
fix: keep minSize, even when size is undefined

### LINKED ISSUE #255: minSize doesn't work
minSize doesn't work when there are more than two split areas.

Versions: 3.0.3 and 4.0.0
Example: https://stackblitz.com/edit/angular-uacvff

### PR DESCRIPTION
**Pull request by Gwe-n**
Fix #255

### CODE REVIEW

**Comment by DerekJDev** [comment]
Any ETA on when this will be pushed?

**Comment by gtteamamxx** [comment]
Any updates?
@beeman

**Comment by Jefiozie** [comment]
Hi @Gwe-n, recently @beeman handed over the maintenance to myself and @SanderElias. 

Could you provide me a update on this PR and resolve the conflicts? After this we will review your PR.

**Review by Jefiozie — APPROVED** [review]
Lgtm

**Comment by Jefiozie** [comment]
@SanderElias could you also do a review

**Review by SanderElias — APPROVED** [review]

**Comment by Jefiozie** [comment]
@all-contributors please add @gwe-n for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
