### PR TITLE
global config settings

### PR DESCRIPTION
**Pull request by pawelwojkiewicz**
This PR resolve the issue from: https://github.com/angular-split/angular-split/issues/166

### CODE REVIEW

**Review by beeman — CHANGES_REQUESTED** [review]

**Comment by beeman** [comment]
@pawelwojkiewicz it looks like this change breaks the other demo pages if the global config is not provided, could you look into this. 

image

**Comment by pawelwojkiewicz** [comment]
Hello beeman! You're right - there was missing @Optional() additional
do @Inject. Now I've added that. I also removed ts-ignore comment. Now
everything should be fine :) Thank you!

sob., 20 lis 2021 o 01:05 beeman ***@***.***> napisał(a):

**Comment by beeman** [comment]
> Hello beeman. You're right - there was missing @optional() additional to @Inject. I've added this. I also removed ts-ignore comment. Now everything should be fine.

Thanks! Can you rebase over the latest main branch? It updated to Angular 13 in the meanwhile

**Comment by pawelwojkiewicz** [comment]
Done.

czw., 25 lis 2021 o 21:52 beeman ***@***.***> napisał(a):

**Review by beeman — APPROVED** [review]

**Comment by Jefiozie** [comment]
@all-contributors please add @pawelwojkiewicz for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Comment by stephanebouget** [comment]
Hello, is there a documentation to see how to use it ?
ty!

**Comment by Harpush** [comment]
> Hello, is there a documentation to see how to use it ? ty!

Before the 18 beta or on beta?

**Comment by stephanebouget** [comment]
> > Hello, is there a documentation to see how to use it ? ty!
> 
> Before the 18 beta or on beta?

On the 18 beta

**Pull request merged**
