### PR TITLE
test: fixed package-lock

### PR DESCRIPTION
**Pull request by SanderElias**
related to issue #435

This package-lock should work on windows. Awaiting result form that.

### CODE REVIEW

**Comment by SanderElias** [comment]
@Harpush @Jefiozie Can you test if `npm install` works for this branch?

**Comment by Harpush** [comment]
@SanderElias After nuking node_modules and trying a clean npm install - seems to work!

**Review by Jefiozie — APPROVED** [review]
LGTM

**Comment by Jefiozie** [comment]
@all-contributors please add @sanderelias for test.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
