### PR TITLE
fix: update to release-it and update changelog

### PR DESCRIPTION
**Pull request by Jefiozie**
Update our tooling to use release-it in favor of release please. This due to generation of changelog

### CODE REVIEW

**Comment by Harpush** [comment]
What will happen to the old changelog?

**Comment by Jefiozie** [comment]
Great question @Harpush , I will make a archive of it so that people still can have a look at it.

**Comment by Harpush** [comment]
Two more things @Jefiozie:
1. The current changelog mentions version 0.0.1 which isn't correct.
2. The site has a changelog page which should show the archive you are about to create too.

**Comment by Jefiozie** [comment]
@Harpush I fixed the problem with version 0.0.1. WHen this PR is merged I will change the componet to also toggle between the archived changelog.

**Comment by Jefiozie** [comment]
Any other points @Harpush or @SanderElias. I would like to land this before v19 update

**Comment by Harpush** [comment]
@Jefiozie I am not sure how the changelog should work but we will have three changelog files now. Just make sure it is all correctly in place with old versions and new versions

**Pull request merged**
