### PR TITLE
feat: improve CI workflow

### PR DESCRIPTION
**Pull request by Jefiozie**
In this Pull Request (PR), we are excited to introduce several enhancements to our Continuous Integration (CI) process. Below is an overview of the newly added functionalities:

**Compliance**: This action aids in handling incoming PRs that may require adjustments beyond just code. 
> Note: The Compliance check is currently failing due to permission issues. This will be resolved once the changes are merged.

**Contributions**: Utilizing the [@all-contributors add bot](https://allcontributors.org/docs/en/bot/usage), this feature automatically posts acknowledgments in the most recent issues and PRs for each contributor's efforts.

**Build**: This action builds both the application and the library.

**Lint**: This step lints the application and library, ensuring code quality and consistency.

**Test**: We've implemented an end-to-end (e2e) testing process.

**Dependency Review**: This function scans dependencies to identify and report on vulnerable packages.

**License**: Scheduled to run annually (or manually), this action updates the License file with the current year.

**Release-Please**: This automates the release process based on specific types of git commits, such as fixes or new features.

Additionally, we have integrated commitlint to validate the commits made on the clients, enhancing the overall quality and consistency of our commit history.

this will close: #375 and #376

### CODE REVIEW

**Comment by Jefiozie** [comment]
Lint will also fail as the PR #382 is not yet merged

**Review by SanderElias — APPROVED** [review]
Looks good to me
1 nit tho, I think we should move all CI?Cd to node 20 now

**Comment by Jefiozie** [comment]
> Looks good to me 1 nit tho, I think we should move all CI?Cd to node 20 now

Should we also build, lint test etc on the main branch?

**Comment by Jefiozie** [comment]
> Looks good to me 1 nit tho, I think we should move all CI?Cd to node 20 now

@SanderElias  I've changed it to node 20.x

**Comment by SanderElias** [comment]
Can this be merged now?

**Comment by Jefiozie** [comment]
@SanderElias  when all actions are green, except complaince, Yes!

**Comment by Jefiozie** [comment]
@all-contributors please add @sanderelias for maintenance.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
