### PR TITLE
Documentation issue: Fix old classNames and components prefix to new one

### LINKED ISSUE #305: Docs: "ui-*" classNames are wrong, should be "as-*"
Hello, thanks for this simple and effective library

**Describe the bug**
Current version of [online documentation](https://angular-split.github.io/documentation) show **obsolete class names and components** with `ui-*` prefix that is now replaced by `as-*` 
image

Here is the docs source file with wrong class names and components to fix
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/src/app/documentation/documentation.component.ts#L184-L210

It has been replaced with new class names like:
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/projects/angular-split/src/lib/component/split.component.scss#L39
https://github.com/angular-split/angular-split/blob/659694376dfa83a6fa4b4e5f42f524e3349e6298/projects/angular-split/src/lib/component/split.component.scss#L10

### PR DESCRIPTION
**Pull request by lf-novelt**
Fix #305: renamed classNames and components name
Changed `ui-` prefix to `as-` prefix

### CODE REVIEW

**Comment by beeman** [comment]
Thanks a lot for your contribution @lf-novelt 👍

**Comment by lf-novelt** [comment]
you're welcome. how does the live version of the documation get updated though? I am still seeing the old names on  https://angular-split.github.io/documentation

**Comment by beeman** [comment]
> you're welcome. How does the live version of the documation get updated though? I am still seeing the old names on https://angular-split.github.io/documentation

I will push an update when I get back at my computer :)

**Comment by beeman** [comment]
@lf-novelt done! Thanks again!

**Comment by lf-novelt** [comment]
great, thanks again for the quick support and reactivity! Much appreciated. Have a good day.

**Comment by Jefiozie** [comment]
@all-contributors please add @lf-novelt for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
