### PR TITLE
ci: use npm instead of yarn

### PR DESCRIPTION
**Pull request by viceice**
fix a regression of 
- #429

### CODE REVIEW

**Comment by viceice** [comment]
it seems we need to relax peer dependencies 😔

**Review by SanderElias — APPROVED** [review]
LGTM, thanks for the PR!

@Jefiozie If everything checks out, this is one less "3rth party". 
Assuming there is no issue with the peerdeps?

**Comment by SanderElias** [comment]
@viceice @Jefiozie 
The problem is that the package lock isn't generated correctly. Because of that, `npm ci` errors out. Not sure how/when that happened.

**Comment by viceice** [comment]
@SanderElias @Jefiozie I fixed the peer dependency issue via upgrading `ngx-bootstrap`[^1]

[^1]: https://github.com/valor-software/ngx-bootstrap?tab=readme-ov-file#compatibility

**Comment by viceice** [comment]
`ngx-bootstrap` is only used for tests, not a dep of the published package

**Comment by Jefiozie** [comment]
@all-contributors please add @viceice for infra.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
